mod ollama;
mod openai;

pub use ollama::{
    OllamaEmbeddingProvider, DEFAULT_OLLAMA_BASE_URL, DEFAULT_OLLAMA_CONNECT_TIMEOUT,
    DEFAULT_OLLAMA_DIMENSIONS, DEFAULT_OLLAMA_MODEL, DEFAULT_OLLAMA_REQUEST_TIMEOUT,
};
pub use openai::{
    OpenAiEmbeddingProvider, DEFAULT_OPENAI_BASE_URL, DEFAULT_OPENAI_CONNECT_TIMEOUT,
    DEFAULT_OPENAI_DIMENSIONS, DEFAULT_OPENAI_MODEL, DEFAULT_OPENAI_REQUEST_TIMEOUT,
};
